project_id = "ikyrgqxvjvnalnrqibyi"

[functions.generate-pdf-content]
verify_jwt = true

[functions.generate-automation]
verify_jwt = true

[functions.generate-resume]
verify_jwt = false

[functions.generate-ebook-chapter]
verify_jwt = true

[functions.generate-complete-ebook]
verify_jwt = false

[functions.generate-design-ai]
verify_jwt = false

[functions.improve-chapter]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.register-referral]
verify_jwt = true

[functions.process-referral-commission]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-catalog-content]
verify_jwt = false

[functions.generate-catalog-image]
verify_jwt = false
